service:
  name: gopher-user-ecomy
  version: v0
port: 8080
grpcPort: 5050
host: ""
basepath: ""
trace: false
apipath: "v1"
debug: false
services:
  registry: ""
  storage: 
    addr: ""
tracing:
  service: ""
  uri: ""
  secret: ""